# Generated by Django 4.1.2 on 2022-10-05 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.AddField(
            model_name='product',
            name='token',
            field=models.CharField(blank=True, default='TTC', max_length=100, null=True),
        ),
    ]
