# Generated by Django 4.1.2 on 2022-10-12 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_transactions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_link', models.CharField(max_length=500, null=True)),
                ('wallet_address', models.CharField(max_length=10000, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='store.product')),
            ],
            options={
                'ordering': ('-added_on',),
            },
        ),
        migrations.DeleteModel(
            name='Transactions',
        ),
    ]
