# Generated by Django 4.1.2 on 2022-10-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_transaction_delete_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='blockash',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
