# Generated by Django 4.1.2 on 2022-10-12 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_transaction_blockash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='blockash',
            new_name='block_hash',
        ),
    ]
