# Generated by Django 4.1.2 on 2022-10-05 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.png', upload_to='')),
                ('trade_mark', models.CharField(default='TURTLE NFT', max_length=255)),
                ('title', models.CharField(default='The #1 source for NFT lookup', max_length=1000)),
                ('slogan', models.TextField(default="Your best choice when you're on the lookup for NFTs.")),
            ],
            options={
                'verbose_name': 'Setting',
            },
        ),
    ]
